- id: sbt-fatal-warnings
  name: Scala fatal warnings
  stages: [commit,push]
  language: python
  entry: sbt-fatal-warnings
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '1.21.0'
- id: sbt-unused-imports
  name: Scala unused imports (+ fatal warnings)
  stages: [commit,push]
  language: python
  entry: sbt-fatal-warnings --add_arg='-Ywarn-unused-import'
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '1.21.0'
- id: sbt-scalafmt
  name: Scalafmt formatting check
  stages: [commit,push]
  language: python
  entry: scalafmt
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '1.21.0'
- id: sbt-scalastyle
  name: Scalastyle style check
  stages: [commit,push]
  language: python
  entry: scalastyle
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '1.21.0'
- id: sbt-scapegoat
  name: Scapegoat static analysis
  stages: [commit,push]
  language: python
  entry: scapegoat
  pass_filenames: false
  always_run: true
  minimum_pre_commit_version: '1.21.0'